version: '3'

services:
  backend:
    build:
      context: ./backend-site
      dockerfile: Dockerfile
    image: trdamp/backend-site:v1

  frontend:
    build:
      context: ./html-static-site
      dockerfile: Dockerfile
    image: trdamp/html-static-site:v1
